### ISSUE TITLE
Metric API proposal to cover typical Kubernetes metrics

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#1001]
**Description**
As outlined in https://github.com/kyma-project/telemetry-manager/issues/972 typical metrics should be easily collactable so that typical kubernetes workload monitoring gets possible. The metrics should be based on the kubletstatsreceiver and k8sclusterreceiver only.
A concrete API proposal is needed on how to enable the metric collection from user side. Hereby, you need to think about which metrics you are usually enabling together as they are always used in combination. Also, the selection via namespaces should be applied to namespace-typical metrics only.
The input name should trigger the right expectations.

**Criterias**
- Concrete API proposal for selecting the typical metrics, outlining which chunk of metrics are getting enabled by which input
- Users should be able to limit metrics to certain namespaces
- Users should be able to enable bigger chunks selectively

**Ideas**
```yaml
  input:
    cluster:
      enabled: true
      namespaces:
        include:
        - myNamespace
    host:
      enabled: true
    runtime:
      enabled: true
      namespaces:
        include:
        - myNamespace
```

**Reasons**

**Attachments**

**Release Notes**

```

```

**Comment by chrkl** [comment]
Our discussions showed that it is hard to split the metrics from `k8sclusterreceiver` and `kubeletstatsreceiver` into the three sections `cluster`, `host`, and `runtime`. We rather propose to have a single input section and give the user the option to chose different resources to be included in the metric output:

```yaml
input:
  runtime:
    enabled: true
    resources:
      - pod
      - container
      - node
      - volume
      - daemonset
      - deployment
      - statefulset
      - quota
      - job
      - hpa
    namespaces:
      include:
      - myNamespace
```

The individual resources should include the following metrics:


### pod

k8s.pod.cpu.time
**k8s.pod.cpu.utilization**
k8s.pod.filesystem.available
k8s.pod.filesystem.capacity
k8s.pod.filesystem.usage
k8s.pod.memory.available
k8s.pod.memory.usage
k8s.pod.network.errors
k8s.pod.network.io
**k8s.pod.cpu.usage**
k8s.pod.phase

### container

k8s.container.cpu_limit
k8s.container.cpu_request
k8s.container.ephemeralstorage_limit
k8s.container.ephemeralstorage_request
k8s.container.memory_limit
k8s.container.memory_request
k8s.container.restarts
**container.cpu.utilization**
**container.cpu.usage**
container.cpu.time
container.filesystem.available
container.filesystem.capacity
container.filesystem.usage
container.memory.usage
**container.cpu.usage**

### node

**k8s.node.cpu.utilization**
**k8s.node.cpu.usage**
k8s.node.filesystem.available
k8s.node.filesystem.capacity
k8s.node.filesystem.usage
k8s.node.memory.available
k8s.node.network.errors
k8s.node.network.io

### volume

k8s.volume.available
k8s.volume.capacity

### daemonset

k8s.daemonset.current_scheduled_nodes
k8s.daemonset.desired_scheduled_nodes
k8s.daemonset.misscheduled_nodes
k8s.daemonset.ready_nodes

### deployment

k8s.deployment.available
k8s.deployment.desired

### statefulset

k8s.statefulset.current_pods
k8s.statefulset.desired_pods
k8s.statefulset.ready_pods
k8s.statefulset.updated_pods

### quota

k8s.resource_quota.hard_limit
k8s.resource_quota.used

### job

k8s.cronjob.active_jobs
k8s.job.active_pods
k8s.job.desired_successful_pods
k8s.job.failed_pods
k8s.job.max_parallel_pods
k8s.job.successful_pods

### hpa

k8s.hpa.current_replicas
k8s.hpa.desired_replicas
k8s.hpa.max_replicas
k8s.hpa.min_replicas

The **bold** marked metrics are already part of the `runtime` input (release 1.17).
