### ISSUE TITLE
New metric input for kyma status as annotation

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#1182]
**Description**
As part of https://github.com/kyma-project/telemetry-manager/issues/728 have an annotation for MetricPipelines ready which will activate the new receiver for collecting kyma module status. 

The annotation might be named like:
```
telemetry.kyma-project.io/kymastats: true
```

**Criterias**
- Have an annotation in place which is disabled by default and can be activated by setting the value to "true"
- If enabled, the new kymastats receiver gets enabled wrapped by the leader-election receiver and will start collecting metrics for all modules
- The receiver is either running in the agent or the gateway, decision pending on that
- The instrumentationScope is defined as for other inputs
- If one MetricPipeline is activating the new input while a second does not, the second pipeline should not export the data
- Have e2e tests in place

**Reasons**

**Attachments**

**Release Notes**

```

```

**Comment by a-thaler** [comment]
A config which works for me:
```
        singleton_receiver_creator:
          auth_type: serviceAccount
          leader_election:
            lease_name: telemetry-metric-agent-kymastats
            lease_namespace: kyma-system
          receiver:
            kymastats:
              auth_type: serviceAccount
              collection_interval: 30s
              module_groups:
              - operator.kyma-project.io
              - connectivityproxy.sap.com
              - operator.sme.sap.com
```
