### ISSUE TITLE
Option to disable pod and/or container metrics

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#1183]
**Description**
As part of https://github.com/kyma-project/telemetry-manager/issues/972 enhance the current runtime input with flags to enable/disable metrics for pods and containers

```yaml
input:
  runtime:
    enabled: true
    resources:
      pod:
        enabled: true
      container:
        enabled: true
```

**Criterias**
- The metrics for pods and containers can be disabled selectively, see API proposal https://github.com/kyma-project/telemetry-manager/issues/1001#issuecomment-2154182359
- By default they are enabled, existing clusters are working as before
- Assure that defaulting logic is guaranteed by e2e tests

**Reasons**

**Attachments**

**Release Notes**

```

```
