### ISSUE TITLE
False positives in FlowHealth status as result of ambigious alert calculations

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#1187]
**Description**
The telemetry-self-monitor collects metrics of all telemetry components and defines alerts on top of them to notify problems via the TelemetryFlowHealth condition.
Recently I stumbled across an "AllTelemetryDataDropped" reason for logs where there was no actual problem. Debugging the metrics I had these findings:

The main scrape loop contain these elements

```yaml
    scrape_configs:
        - job_name: kubernetes-service-endpoints
          relabel_configs:
            ...
            - source_labels: [__meta_kubernetes_namespace]
              target_label: namespace
              action: replace
            - source_labels: [__meta_kubernetes_pod_node_name]
              target_label: node
              action: replace
          metric_relabel_configs:
            - regex: ^(receiver|exporter|directory|service_instance_id|service_version|transport|service_name|alertname|job|instance|namespace|node)$
              action: labeldrop
```

You can see that the namespace and pod labels are getting enriched, to just get dropped afterwards, which is redundant.
Much more relevant is the instance/pod label drop. A metric gets collected from multiple pods, like the `fluentbit_output_dropped_records_total` metric. As the instance and pod label get dropped, the time series data gets just recorded after each other not knowing about the instance. So if one pod had a data drop in the past (positive but not increasing value) while the other is not (having a constant zero), you will see more a gauge series then a counter. And the resulting alert rule which is applying a rate function will get a constant rate for the metric, resulting in an alert.

**Expected result**
Expected is that we keep the pod flavor and use a proper aggregation in the alert rule, so getting the rate per pod (turning the counter into a gauge value) and then take the max to determine if there is a an actual increase currently.

The change need to be applied to all metric collections and the alert rule verified for proper aggregation.

**Actual result**
The timeseries of pods are mixed up without any aggregation and will not reflect the truth anymore

**Steps to reproduce**

**Troubleshooting**

**Release Notes**

```

```
