### ISSUE TITLE
Panic on missing TLS settings: Nil pointer dereference

### ISSUE THREAD

**Issue by TeodorSAP** [kyma-project/telemetry-manager#1205]
**Description**

When either one of the `cert` or `key` fields are missing from the TLS configuration of a pipeline, the telemetry-manager panics, since a nil pointer is being dereferenced in the validation process.

Related (already solved) issue: https://github.com/kyma-project/telemetry-manager/issues/1192

**Expected result**

An error message should be displayed in the Condition/Reason result.

**Actual result**

telemetry-manager pod panics

**Steps to reproduce**

Create a pipeline with either the `cert` or `key` field missing

Example:
```yaml
spec:
   tls:
      cert: "PEM CERTIFICATE"
      ca: "PEM CA CERTIFICATE"
```

**Troubleshooting**

**Release Notes**

```

```
