### ISSUE TITLE
Invalid URL endpoint in otlp-http output skips config generation without propagating the problem into the status

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#1270]
**Description**

Assumed you have a successful running TracePipeline and you add a second one.
Assumed the new TracePipeline uses an otlp-http configuration like this:
```
spec:
  output:
    otlp:
      endpoint:
        valueFrom:
          secretKeyRef:
            key: apiurl
            name: mySecret
            namespace: myNamespace
      path: v2/otlp/v1/traces
      protocol: http
```
having then the actual value quoted with '', like when creating the secret with `kubectl create secret generic test --from-literal apiurl="'https://icke.com'"`

then the telemetry-manager will fail the reconcilation of the new pipeline with following log message. It will not touch the agent config and keep the pipeline status healthy.

```
{"level":"ERROR","timestamp":"2024-07-12T15:46:05Z","caller":"controller/controller.go:324","message":"Reconciler error","context":{"controller":"metricpipeline","controllerGroup":"telemetry.kyma-project.io","controllerKind":"MetricPipeline","MetricPipeline":{"name":"dynatrace"},"namespace":"","name":"icke","reconcileID":"30c7b93e-809e-4eec-88ff-20a025b4e4de","error":"failed to reconcile metric gateway: failed to create collector config: failed to make otlp exporter config: failed to make env vars: parse \"'https://icke.com'\": first path segment in URL cannot contain colon"}}
```

**Expected result**

The pipeline has the "ConfigurationGenerated" status set to "false" with a meaningful reason telling me that I provided a bad URL

**Actual result**
It silently ignores my pipeline, the gateway continues to run, but data will never arrive

**Steps to reproduce**

**Troubleshooting**

**Release Notes**

```

```
