### ISSUE TITLE
Unify namespace selector in LogPipeline input

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#1395]
**Description**

With https://github.com/kyma-project/telemetry-manager/issues/767 the LogPipeline will be promoted to a beta API. For that, the API of the input section needs to get aligned with the Trace/MetricPipeline APIs. 

```yaml
input:
  application:
    containers: # mutually exclusive
      exclude:
        - ns1
        - ns2
      include:
        - ns3
        - ns4
    namespaces: # mutually exclusive
      system: true
      exclude:
        - ns1
        - ns2
      include:
        - ns3
        - ns4
```

New API proposal:
```yaml
input:
  runtime:
    enabled: true # was added already
    containers: # stays as is
      exclude:
        - ns1
        - ns2
      include:
        - ns3
        - ns4
    namespaces: # mutually exclusive, defaulting will render system namespaces. Set to {} if namespaces should be included
      exclude:
        - ns1
        - ns2
      include:
        - ns3
        - ns4
```

**Criterias**
- The LogPipeline beta API is consistent
- The beta API stays compatible to alpha via the conversion webhook

**Reasons**

**Attachments**

**Release Notes**

```

```
