### ISSUE TITLE
Document and harmonize metric scraping with networkpolicies

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#1516]
**Description**
Assumed you have a deny all networkpolicy in your cluster and you enable the prometheus/istio input for a MetricPipeline. By design, this will not work as the metrics agent cannot access the pod to scrape.

The typical log output in the agent will be
```txt
{"level":"warn","ts":1728575156.2198486,"caller":"internal/transaction.go:128","msg":"Failed to scrape Prometheus endpoint","kind":"receiver","name":"prometheus/istio","data_type":"metrics","scrape_timestamp":1728575146218,"target_labels":"{__name__=\"up\", instance=\"10.96.0.212:15090\", job=\"istio-proxy\"}"}
{"level":"warn","ts":1728575170.0367186,"caller":"internal/transaction.go:128","msg":"Failed to scrape Prometheus endpoint","kind":"receiver","name":"prometheus/app-services","data_type":"metrics","scrape_timestamp":1728575170031,"target_labels":"{__name__=\"up\", instance=\"10.96.0.212:8080\", job=\"app-services-secure\", service=\"my-app\"}"}
```

Please introduce a troubleshooting guide for this scenario, outlining how to define a proper NetworkPolicy like:
```yaml
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kyma-system
      podSelector:
        matchLabels:
          app.kubernetes.io/name: telemetry-metric-agent
  - ports:
    - port: 8080 #custom app port
      protocol: TCP
    - port: 15090 #istio port
      protocol: TCP
```

Also, introduce a better label for the agent pod abstracting the logical feature, like: "telemetry.kyma-project.io/metric-scrape" and use it in the policy instead. That will allow us to move the functionality to a different component at a later time.
