### ISSUE TITLE
Add new inputs for daemonset/deployment/statefuleset/job being disabled by default

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#1521]
As part of https://github.com/kyma-project/telemetry-manager/issues/972 enhance the current runtime input with new selector for workload metrics. It should be disabled by default.

```yaml
input:
  runtime:
    enabled: true
    resources:
      ... 
      daemonset:
        enabled: false
      deployment:
        enabled: false
      statefulset:
        enabled: false
      job:
        enabled: false
```
Tasks:
- Add new feature
- Verify proper instrumentation scope is in use
- Enhance E2E test for runtime input (to assure compatibility of the emmitted metrics)
- Check that tests are not getting more flaky
- Check resource attributes, are they meaningful?
- Drop metrics if disabled in selector
- Add documentation to the gateway docu
