### ISSUE TITLE
A runtime input with namespace selector will filter out namespace-less metrics

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#1549]
**Description**

A MetricPipeline with input:
```yaml
    runtime:
      enabled: true
      namespaces:
        include:
        - cap
      resources:
        container:
          enabled: true
        node:
          enabled: true
        pod:
          enabled: true
        volume:
          enabled: true
```

so having node metrics enabled and a namespace selector defined, will filter out all node metrics as they do not belong to any namespace.

**Expected result**
The namespace selector will not be effective for namespace-less metrics as I explicitly enabled the selector

**Actual result**
Namespace-less metrics are getting filtered out

**Steps to reproduce**

**Troubleshooting**

**Release Notes**

```

```
