### ISSUE TITLE
kyma.resource.status.state metric gets filtered by namespace filter

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#1784]
**Description**
I have a MetricPipeline like that:

```yaml
spec:
  input:
    otlp:
      namespaces:
        include:
        - cap
    runtime:
      enabled: true
      namespaces:
        include:
        - cap
        - observability
```

The pipeline exports the health metric "kyma.resource.status.conditions" but not "kyma.resource.status.state". The missing metric is namespace specific (kyma-system) and most probably gets blindly filtered out by the otlp input namespace selector.

**Expected result**

The metric is always emmitted
