### ISSUE TITLE
OTLP Logs: Label support

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#1802]
**Description**
As part of https://github.com/kyma-project/telemetry-manager/issues/556, a compatible way is required to enrich logs with label metadata of the underlying pod. That feature is currently supported with the fluentbit setup in combination with the `input.​application.​dropLabels` attribute.

**API Proposal**

Enriching all logs with all labels of the related pods seem like a waste of resources, as usually you will filter by very well-defined labels only. Filtering by annotations seems even irrelevant and very costly as annotations tend to have bigger values.
Also, enriching telemetry data with selective labels of the underlying pods seem to be equivalent relevant for all signal types, not only logs. Think of the correlation situation. That's why the proposal introduce a fully new section on root level for the LogPipeline, to be used at a later time for all pipeline types.

```yaml
apiVersion: telemetry.kyma-project.io/v1alpha1
kind: LogPipeline
metadata:
  name: logs
spec:
  input:
    application:
      dropLabels: false # if actively configured when otlp output is used, the configuration should be treated as invalid
      keepAnnotations: true # if actively configured when otlp output is used, the configuration should be treated as invalid
  enrich:
    podLabels:
    - myLabel1
    - myLabel2
    - myLabelPrefix*
    cloudAttributes:
      enabled: true
    serviceName:
      enabled: true
  transform:
    ...
  filter:
    ...
  output:
    otlp:
       ...
```

**Criterias**
- All API is available only behind the OTLP Log feature gate, even if the solution will be generic
- The old attributes for labels and annotations are not supported in OTLP mode
- There is a new API independent of input or output
- The new API supports specifying a label list (with wildcard support if possible using standard processors)
- The specified labels will be attached as resource attributes to all logs related logs if available on the pod
- The resource attributes follow the semantic conventions defined here: https://opentelemetry.io/docs/specs/semconv/attributes-registry/k8s/#k8s-pod-label

**Comment by hisarbalik** [comment]
After a discussion about the new API proposal, the feature will be moved to a global place in the Telemetry pro signal type.

```yaml
apiVersion: operator.kyma-project.io/v1alpha1
kind: Telemetry
metadata:
  name: default
  namespace: kyma-system
spec:
  metric:
     presets:
       podLabels:
       - name: myLabel1
       - name: myLabel2
       - prefix: myLabelPrefix
       cloudAttributes:
         enabled: true
       serviceName:
         enabled: true
     transform:
       ...
     filter:
       ...
  log:
     presets:
       podLabels:
       - name: myLabel1
       - name: myLabe2
       - prefix: myLabelPrefix
       cloudAttributes:
         enabled: false
       serviceName:
         enabled: false
     transform:
       ...
     filter:
       ...
```
