### ISSUE TITLE
Support for container restart metric as part of runtime input

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#1882]
**Description**
An important indicator for a problematic situation is the ratio of container restarts. For that, exposing the [k8s.container.restarts](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/k8sclusterreceiver/documentation.md#k8scontainerrestarts) metric as part of the MetricPipeline runtime input will be good.

```yaml
    runtime:
      enabled: true
      resources:
        container:
          enabled: true
```

Criterias:
- Having the runtime input enabled and the container subselector is enabled, container restart metrics are getting shipped
