### ISSUE TITLE
OTLP Logs: Parser support for unstructed logs

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#1890]
**Description**
 The current fluentbit based LogPipeline supports parsing of unstructured logs with a custom format. Also a multi-line parsing is supported. Goal is to gain feature parity and support this feature for the OTLP based approach as well.

The filelogreceiver of the otel-collector supports parsing of log attributes using a [regexp parser](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/docs/operators/regex_parser.md). Also it support multiline parsing using a recombine operator, see also [splunks helm chart](https://github.com/signalfx/splunk-otel-collector-chart/blob/main/helm-charts/splunk-otel-collector/values.yaml#L621).

Goal: Provide an easy way to configure parser and multi-line parser for LogPipelines, so that unstructured logs can become structured even if they are not JSON based.

Criterias:

- [x] Decide if configuration should be supported per LogPipeline input or globally only
- [x] Restriction to specific pods is probably needed, see also splunks helm chart for verification
- [ ] Regexps with wrong syntax should fail fast by getting a configuration error
- [ ] Provide examples for typical Java logs

Tasks:
- [ ] Move stanza chain into a transform block
- [ ] API for regexp parser
- [ ] API for multi-line parser
- [ ] Built-in parsers

API Propsal:

```yaml
apiVersion: operator.kyma-project.io/v1alpha1
  kind: Telemetry
  metadata:
    name: default
    namespace: kyma-system
  spec:
    log:
      parsers:
           - namespaceSelector:
                matchExpressions:
                - key: operator.kyma-project.io/managed-by:
                  operator: NotIn
                  values:
                  - kyma
               matchLabels:
                  role: backend
             podName:
                regex: buttercup-app-.*
            containerName:
              value: server
            regex: '^Host=(?P<host>[^,]+), Type=(?P<type>.*)$'
            firstEntryRegex: '^[^\s].*'
            combineWith: ""
```

Hereby, namespaces are supported based on a selector while pod and container names not. Pod and containers are very dynamic and frequent changes in selector results will lead to re-starts of the agent which needs to be limited to a minimum.

**Reasons**

**Attachments**

**Release Notes**

```

```
