### ISSUE TITLE
Support scraping subsets of envoy metrics for the istio input

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#1943]
**Description**

The MetricPipeline Istio input supports scraping metrics from all envoys (Istio sidecar) running in a cluster in a convenient way. Hereby, only `istio_*` metrics are getting collected to keep the data footprint as low as possible. There are a magnitude of `envoy_*` metrics available as well which are used in more advanced use cases and usually a specific selection is needed only.

**Goal**
Introduce an API to enable scraping subsets of `envoy_*` metrics

**Criterias**

- As part of the MetricPipeline `Istio` input you can specify additional metric prefixes to scrape
- Multi-pipeline scenario will respect individual selections, having a subset enabled in pipeline A will not reveal in pipeline B
- Documentation is available on how to see which metrics are available and how to enable them

**API Proposal**

```yaml
apiVersion: telemetry.kyma-project.io/v1beta1
kind: MetricPipeline
metadata:
  name: cls
spec:
  input:
    istio:
      enabled: true
      additionalMetrics:
      - name: envoy_myMetric
      - namePrefix: envoy_group_
output:
  ...
```

Enabling just all envoy is also acceptable, even in the global config, if the solution sounds more smart.

**Comment by hisarbalik** [comment]
Proposed New API

```yaml
apiVersion: telemetry.kyma-project.io/v1alpha1
kind: MetricPipeline
metadata:
  name: sample
spec:
  input:
    runtime:
      enabled: false
    prometheus:
      enabled: false
    istio:
      enabled: true
      namespaces:
        exclude:
        - kyma-system
        - kube-system
        - istio-system
      envoyMetrics:
         enabled: true
```

A new configuration option has been introduced in the Istio input section: `envoyMetrics.enabled`. This option enables the collection of Envoy metrics. By default, the value is set to `false`.

When `envoyMetrics.enabled` is set to `true` (and the Istio input is also enabled), the system will scrape metrics that are prefixed with `envoy_*`, in addition to the existing `istio_*` metrics.
