### ISSUE TITLE
Support annotations for trace/log/metric gateway

### ISSUE THREAD

**Issue by dennis-ge** [kyma-project/telemetry-manager#1944]
**Description**

Hi, it would be nice if configuring deployment/pod annotations is possible for the trace/log/metric otel-collector. 

**Reasons**

I was experimenting with the telemetry-manager  and encountered the following problem:

- I successfully installed the telemetry manager 1.35.0 from the [release page](https://github.com/kyma-project/telemetry-manager/releases/download/1.35.0/telemetry-manager.yaml).
- Next, I wanted to install a basic trace pipeline. This, however, failed since a kyverno policy in my cluster blocked the installation. The policy is something internal and I can take of fixing it.
```json
{"level":"ERROR","timestamp":"2025-03-14T12:49:46Z","caller":"controller/controller.go:341","message":"Reconciler error","controller":"tracepipeline","controllerGroup":"t
elemetry.kyma-project.io","controllerKind":"TracePipeline","TracePipeline":{"name":"sample-otel"},"namespace":"","name":"sample-otel","reconcileID":"1cc5beba-a5de-48ad-87
08-963098a4b131","error":"failed to reconcile trace gateway: failed to apply gateway resources: failed to create deployment: admission webhook \"validate.kyverno.svc-igno
re\" denied the request: \n\nresource Deployment/otel-demo/telemetry-trace-gateway was blocked due to the following policies \n\n<...>'\n"}
```

Nevertheless, it would be nice if I could configure additional annotations for the trace gateway which would allow me to skip the kyverno policy. So that in the end my annotations show up in the trace gateway

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trace-gateway
  annotations:
    policy/<my kyverno policy>: skip
spec:
  template:
    metadata:
      annotations:
        policy/<my kyverno policy>: skip
```

**Criterias**
- There is a way to configure annotations and labels which are getting applied to all telemetry Deployment and Dameonset
- There is a way to configure annotations and labels which are getting applied to all telemetry Pods

**API Proposal**

```yaml
apiVersion: operator.kyma-project.io/v1alpha1
kind: Telemetry
metadata:
    name: default
    namespace: kyma-system
spec:
  pods:
    annotations:
      myAnno: icke
    labels:
      myLabel: Icke
  workloads:
    annotations:
      myAnno: icke
    labels:
      myLabel: Icke
```

Criterias:
- Propose an API and align it with the reporter, it must not be the business API (it is needed for manual deployments only)
- Implement the API
- Have documentation
- Have relevant tests in place
