### ISSUE TITLE
Support for tainted worker pool nodes by having tolerations defined for DaemonSets

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#1962]
**Description**

When using an additional worker pool you usually want to avoid to run unnecessary workloads on these pools. You might have specialised/expensive machines where only workload should run which is really required. To achieve that, you can use the [taint/tolerations ](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/)mechanism where you taint a node and run only pods which are tolerating that taint.
Having a node tainted, will cause the telemetry module daemonsets to not run anymore on these specialized nodes. However, collecting logs and metrics is a requirement which you usually would still expect on such nodes.
A typical solution to the problem is to declare the important DaemonSets with generic tolerations like:
```yaml
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
```

Goal: Have tolerations for the DaemonSets in place which by default will schedule pods on all nodes
