### ISSUE TITLE
Support metrics for allocatable node resources

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#1974]
**Description**

With the current "runtime" input of a MetricPipeline, you will get CPU usage per node but you have no chance to identify how much CPU is available on a node and with that you cannot give an indicator on how much the CPU is really exhausted.

The k8s node itseld is providing this information as part of the node status:
```yaml
status:
  allocatable:
    cpu: 3920m
    ephemeral-storage: "78976460534"
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 14932760Ki
    pods: "110"
  capacity:
    cpu: "4"
    ephemeral-storage: 81184684Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 16083736Ki
    pods: "110"
```
Hereby, the [k8sclusterreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/k8sclusterreceiver#configuration) provides an option to report the allocatable values, so that these metrics seem to be valueable to export as well by default:
- k8s.node.allocatable_cpu
- k8s.node.allocatable_memory
- k8s.node.allocatable_pods

On base of this, dashboards can visualize the node CPU and memory usage with limits in place as well the pod usage.

**Reasons**

**Attachments**

**Release Notes**

```

```
