### ISSUE TITLE
OTLP Logs: Istio Access log enrichment

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#1977]
**Description**

This story is part of https://github.com/kyma-project/telemetry-manager/issues/1899.
The istio access logs via OTLP will have a good base format, however, further enrichment logic is needed to remove Istio specificas and have the full otel feature set used. That cannot be achieved on base of the Istio API and an additional transformation is needed. The idea is to re-use the log gateway for this task.

The goal is to detect Istio access logs, remove Istio specific attributes and enrich missing things.

Criterias:
Istio Access logs emitted by the kyma telemetry module will:
- have a proper instrumentation scope
- have a proper severity
- do not contain istio specific attributes
Additionally, it will be great to align it with Istio traces and set the instrumentation scope there as well accordingly.

At he end some processor like this is needed:
```yaml
    transform/enrich-istio:
      error_mode: ignore
      log_statements:
        - context: log
          conditions:
            # Only transform actual istio logs
            - attributes["kyma.module"] == "istio"
          statements:
            # Enrich instrumentation scope
            - set(instrumentation_scope.version, "<telemetry version>")
            - set(instrumentation_scope.name, "io.kyma-project.telemetry/istio")
            
            # Enrich severity
            - set(severity_text, "INFO")
            - set(severity_number, 9)

            # Separate protocol name and version
            - set(attributes["network.protocol.version"], attributes["network.protocol.name"]) where IsMatch(attributes["network.protocol.name"], "^.+/.+$$") == true
            - replace_pattern(attributes["network.protocol.name"], "^(.+)/.+$$", "$$1") where attributes["network.protocol.name"] != ""
            - replace_pattern(attributes["network.protocol.version"], "^.+/(.+)$", "$$1") where attributes["network.protocol.version"] != ""

            # Separate server and client addresses from port
            - replace_pattern(attributes["server.address"], "^(.+):.+$$", "$$1") where attributes["network.protocol.name"] != ""
            - set(attributes["client.port"], attributes["client.address"]) where IsMatch(attributes["client.address"], "^.+:.+$$") == true
            - replace_pattern(attributes["client.address"], "^(.+):.+$$", "$$1") where attributes["client.address"] != ""
            - replace_pattern(attributes["client.port"], "^.+:(.+)$$", "$$1") where attributes["client.port"] != ""

            # delete istio specificas
            - delete_key(resource.attributes, "cluster_name")
            - delete_key(resource.attributes, "log_name")
            - delete_key(resource.attributes, "zone_name")
            - delete_key(resource.attributes, "node_name")
 
            # delete istio log marker attribute
            - delete_key(attributes, "kyma.module") where attributes["kyma.module"] == "istio"
   ```

Proposal: Have a new processor in the kyma otel-collector distribution which encodes the logic with some simple configuration. Proper unit testing can be done and e2e tests can focus on happy paths.
