### ISSUE TITLE
OTLP Logs: Istio access logs noise filter

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#1978]
**Description**
This story is part of https://github.com/kyma-project/telemetry-manager/issues/1899.

Istio is used by the telemetry module itself and with that a lot of access logs are being produced which relates to applications pushing telemetry data or receiving. That communication usually is not of interest at all for users and should get filtered out by default.

Goal: Filter out access logs related to communication with the telemetry module itself

Criterias:
No access logs are emmitted by the telemetry module which are related to communication:
- to or from any telemetry component

At the end, a processor like this is needed:
```yaml
    filter/drop-noisy-logs:
      logs:
        log_record:
          - attributes["kyma.component"] == "istio" and IsMatch(attributes["server.address"], "telemetry-otlp-(traces|metrics|logs)\\.kyma-system.*") == true
          - attributes["kyma.component"] == "istio" and resource.attributes["k8s.namespace.name"] == "kyma-system" and IsMatch(resource.attributes["k8s.deployment.name"], "telemetry-(metric|log|trace)-gateway") == true
          - attributes["kyma.component"] == "istio" and resource.attributes["k8s.namespace.name"] == "kyma-system" and IsMatch(resource.attributes["k8s.daemonset.name"], "telemetry-(metric|log|trace)-agent") == true
          - attributes["kyma.component"] == "istio" and attributes["http.request.method"] == "GET" and attributes["http.direction"] == "inbound" and IsMatch(attributes["user_agent.original"], "vm_promscrape") == true
          - attributes["kyma.component"] == "istio" and attributes["http.request.method"] == "GET" and attributes["http.direction"] == "inbound" and IsMatch(attributes["user_agent.original"], "kyma-otelcol\\/.*") == true
          - attributes["kyma.component"] == "istio" and attributes["http.request.method"] == "GET" and attributes["http.direction"] == "outbound" and IsMatch(attributes["server.address"], "healthz\\..+") == true and IsMatch(attributes["url.path"], "\\/healthz\\/ready") == true
```
