### ISSUE TITLE
OTLP Logs: Improved body handling for log agent

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#2003]
**Description**
If a log payload is in JSON, the log agent tries to parse it. On success, the JSON payload stays in the body and gets replaced by the log message only if the proper "message" attribute gets found.
I suggest to not keep the body on successful parsing, as all attributes got populated into log attributes. If you still want to keep the original payload, you can use the "original" field.

The "original" attribute might be renamed to "log.original" to not have it as root level attribute being in conflict with customer attributes. The log prefix is in use anyway.

-> move instead of copy the body to log.original

```yaml
- id: copy-body-to-attributes-original
         type: move
         from: body
         to: attributes.log.original
```
