### ISSUE TITLE
OTLP Logs: Support trace parsing

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#2004]
**Description**

The log agent transforms a log message from stdout into an OTLP log record. Hereby, it already does several things to populate the main attributes like timestamp, body and severity. However, one last attribute set is missing and cannot get populated, the trace fields.

Please add a trace parser to the change filling the standard attributes:
```yaml
- type: trace_parser
  trace_id:
    parse_from: attributes.trace_id
  span_id:
    parse_from: attributes.span_id
  trace_flags:
    parse_from: attributes.trace_flags
```

Additionally, support for traceparent might be handy. In case an application prints the header.

```yaml
- type: regex_parser
  regex: '^[0-9a-f]{2}-(?P<trace_id>[0-9a-f]{32})-(?P<span_id>[0-9a-f]{16})-(?P<trace_flags>[0-9a-f]{2})$'
  parse_from: attributes.traceparent
  trace:
    trace_id:
      parse_from: attributes.trace_id
    span_id:
      parse_from: attributes.span_id
    trace_flags:
      parse_from: attributes.trace_flags
```

Criterias:
- Add support for most common trace id usage in logs
- Have e2e tests in place
