### ISSUE TITLE
Configurable cluster name and uid

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#2039]
**Description**

All telemetry data emmitted by the telemetry module has attached a k8s.cluster.name resource attribute, which is a great unification. However, in combination with tools like Dynatrace which instrument workloads and already set the cluster name upfront, therecan be a misalignment and one of the two parties need to get adjusted.
It will be great if the telemetry module can be adjusted to a custom cluster name.

Also, the k8s.cluster.uid is not attached at the moment. Here, there is a strict rule which ID to use and this will be the same ID across tooling, so please attach it as well: https://opentelemetry.io/docs/specs/semconv/resource/k8s/

Goal: Attach k8s.cluster.uid and have k8s.cluster.name configurable

**API Proposal**

```yaml
operator.kyma-project.io/v1alpha1
kind: Telemetry
metadata:
    name: default
    namespace: kyma-system
spec:
  enrichments:
    cluster:
      name: myValue
    extractPodLabels:
      - keyPrefix: app.kubernetes.io
 ```
