### ISSUE TITLE
Log Agent is not restarted when referenced secret in LogPipeline is updated

### ISSUE THREAD

**Issue by shorim** [kyma-project/telemetry-manager#2135]
**Description**
Whenever a secret which is referenced in a LogPipeline is updated, the Log Gateway Pods are restarted and use the new values in the secret. However, the Log Agent Pod is not restarted and continues using the old values of the secret. It is important that the Log Agent is reconciled whenever the secret is updated especially because of credentials rotations.

**Expected result**
When a referenced secret in a LogPipeline is updated, the Log Agent restarts and use the new values of the secret.

**Actual result**

When a referenced secret in a LogPipeline is updated, the Log Agent does not restart and continue using the old values of the secret.

**Steps to reproduce**

1. Create a LogPipeline which uses values from a secret:

```
cat <<EOF | kubectl apply -f -
apiVersion: telemetry.kyma-project.io/v1alpha1
kind: LogPipeline
metadata:
  name: cls
spec:
  output:
    otlp:
      endpoint:
        valueFrom:
          secretKeyRef:
            name: $CLS_SECRET_NAME
            namespace: $CLS_SECRET_NAMESPACE
            key: $CLS_SECRET_ENDPOINT
      tls:
        insecure: false
        cert:
            valueFrom:
                secretKeyRef:
                    name: $CLS_SECRET_NAME
                    namespace: $CLS_SECRET_NAMESPACE
                    key: $CLS_SECRET_CERT
        key:
            valueFrom:
                secretKeyRef:
                    name: $CLS_SECRET_NAME
                    namespace: $CLS_SECRET_NAMESPACE
                    key: $CLS_SECRET_CERTKEY
      protocol: grpc
EOF
```

2. Update the secret
3. Notice that that the Log Gateway is restarted, but the Log Agent doesn't restart

**Troubleshooting**

**Release Notes**

```

```
