### ISSUE TITLE
Disabled agent features do not remove the agent

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#336]
**Description**
I have a MetricPipeline (or LogPipeline) defined like that:

```
apiVersion: telemetry.kyma-project.io/v1alpha1
kind: MetricPipeline
metadata:
  name: icke
spec:
  input:
    application:
      runtime:
        enabled: true
  output:
    ...
```
which results in a agent and gateway deployment and all is working as expected.
When disabling the runtime at a later time:
```
  input:
    application:
      runtime:
        enabled: false
```

the agent will not get deleted and continues collecting the runtime data. Indeed, the gateway is filtering out the data and the actual result is as expected. However, removing the agent will save money. Also, the agent uses the last applied config and will send runtime data, but will not scrape istio metrics for example. That is inconsistent.

**Expected result**

The agent gets deleted and stops collecting runtime data.

**Actual result**
The agent stays (as well as the config) in an unattended mode (not being reconciled anymore) and it continues to collect data

**Implementation Hints**
The OTel collector's resource management is in the `internal/resources/otelcollector` pkg. Right now, it has `ApplyAgentResources` and `ApplyGatewayResources` functions available. To add `DeleteAgentResources`, we need to separate making different kinds of resources (RBAC, Services, Deployment/DaemonSet, etc.) from what we do with them (like creating or updating). This change will make it easier to add the option to delete without repeating the code.

**Steps to reproduce**

**Troubleshooting**
