### ISSUE TITLE
Increase scrape interval to 30s by default

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#337]
**Description**
The scrape interval for the workload and istio scraping is configured with 10s hardcoded. From the experience with the kyma monitoring stack, a 30s interval was accepted for now and will save a lot of data/money. Making that setting configurable can be a future activity.

**Expected result**
Scraping should happen every 30s only to save money

**Actual result**
It is configured to 10s

**Steps to reproduce**
Create a MetricPipeline:
```yaml
apiVersion: telemetry.kyma-project.io/v1alpha1
kind: MetricPipeline
metadata:
  name: icke
spec:
  input:
    application:
      istio:
        enabled: true
      prometheus:
        enabled: true
      runtime:
        enabled: false
  output:
    ...
```

Check the generated agent config and see the scrape interval settings

**Troubleshooting**
