### ISSUE TITLE
Do not override restartedAt pod annotations in the spec template

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#379]
**Description**
There are situations were external components like to restart the components of the telemetry module like fluentbit. A common approach seem to add an annotation to the pod template of the component like for example:
```yaml
        istio-operator.kyma-project.io/restartedAt: "2023-08-17T13:36:09Z"
        kubectl.kubernetes.io/restartedAt: 2023-08-07 10:35:57.004509102 +0000 UTC
          m=+435681.673771706
```

Such annotation will trigger a restart but also documents the trigger.

At the moment the telemetry manager will not respect such annotations and just override them. There were situations were it got reconciled even before the kubernetes controller was picking up the change, so that no restart was happening.

Criteria:
- Annotations on the pod template for restarts will be respected and not removed by the manager

**Reasons**

**Attachments**
