### ISSUE TITLE
Determine system namespaces by label

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#380]
**Description**

After https://github.com/kyma-project/community/issues/922 is aligned and realized, the new contract of identifying managed namespaces by label should be leveraged as much as possible to avoid any hardcoding of namespaces. With the modularization of kyma, managed namespaces are created dynamically and so a dynamic filter is the perfect fit.

With that, all input sections of the pipelines should support a new way of selecting and defaulting namespaces.

So instead of using the old way of namespace selection like in:
```yaml
    namespaces: # 'system' gets removed, instead a default exclude list gets generated
      exclude:
        - ns1
        - ns2
      include:
        - ns3
        - ns4
```

We should introduce a new element:
```yaml
  namespaceSelector:
    matchExpressions:
    - key: operator.kyma-project.io/managed-by:
      operator: NotIn
      values:
      - kyma
   matchLabels:
        role: backend
 ```

Additionally, any guides like for Dynatrace where managed namespaces are filtered should get adjusted to use the selectors.

Criterias:
- When running in a managed cluster, the managed namespaces should be determined by label selectors only, no namespace hardcoding
- selectors in pipelines should default to exclude managed namespaces
- The old namespace selection should overrule the new selectors, to keep compatibility
- There is no hardcoded list of namespaces in the source code
- Guides are adjusted to also use selectors instead of hardcoding

**Reasons**

**Attachments**
