### ISSUE TITLE
Reflect module deletion in module state

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#381]
**Description**
The telemetry CRD already provides advanced status handling as introduced by https://github.com/kyma-project/kyma/issues/17158
However, the status does not reflect the phase of being in module deletion and especially the phase of being stucked in deletion by having existing Pipeline CRs in the cluster.

Goal: Improve the status to include the phase of deletion and being stucked in deletion.
As reference [btp-manager](https://github.com/kyma-project/btp-manager/blob/main/docs/contributor/02-10-operations.md) and [serverless-manager](https://github.com/kyma-project/serverless-manager/blob/main/docs/user/resources/06-20-serverless-cr.md) can be used.

Idea:
```yaml
status:
  state: "Ready" # switches to "Deleting" in both situations (Deletion and StuckInDeletion)
  endpoints:
    traces:
      grpc: "http://telemetry-otlp-traces...:4317"
      http: "..."
  conditions:
    - type: XXXComponentsHealthy
       status: `true` #stays in true in success case, switches to false when blocked (and later back to true when blocking is fixed)
       reason: XXXGatewayReady # switches to "DeletionBlocked" and "NoPipelinesDeployed"
```

Criterias:
- For the user it is obvious that the deletion is blocked because of exiting pipeline resources
- Tests are added
- New status is added to documentation
- OPtional the problematic situation (StuckInDeletion) is available as k8s event

**Reasons**

**Attachments**
