### ISSUE TITLE
Manual scaling for trace and metric gateway

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#430]
**Description**
The current gateway setup is limited to a maximal throughput. If that is not sufficient, data will be started to refused. To support larger setups, scaling options are required. The simplest form is to have an API allowing to configure a fixed amount of instances. The API should be designed to support auto-scaling options in future.

**API Proposal**
Telemetry CR
```yaml
trace:
  gateway:
    scaling:
      strategy: static
      static:
         replicas: 5
metric:
  gateway:
    scaling:
      strategy: auto
      auto:
        minReplicas: 2
        maxReplicas: 5
  agent:
    resources:
      limits:
        cpu: 100m
        memory: 384Mi
```

**Criterias**
- As a user I can fix the amount of replicas manually via an API
- The API is well documented and outlines the limitations related to my settings
- The API can be extended with auto scaling options in future
- Env tests are assuring that no regression can happen to the new functionality
- The new API is available in the related kyma dashboard views

**Reasons**
A limited troughput will prevent adoption for larger setups

**Attachments**
