### ISSUE TITLE
Namespace filtering support per metric pipeline

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#514]
**Description**

The MetricPipeline inputs should usually not be enabled for system namespaces and should allow even a custom namespace selection.

```YAML
kind: MetricPipeline
apiVersion: telemetry.kyma-project.io/v1alpha1
metadata:
  name: myPipeline
spec:
  input: # Metrics will be received via OTLP to the gateway always. Additionally you can enable different inputs to send additional metrics to the gateway. Metrics are selected based on labels
    prometheus:
      enabled: false
      namespaces: 
        include: []
        exclude: []
        system: false 
    runtime: # (container runtime) activates cadvisor scraping (kubeletreceiver)
      enabled: false
      namespaces: 
        include: []
        exclude: []
        system: false 
    istio:
      enabled: false
      namespaces: 
        include: []
        exclude: []
        system: true 
    otlp:
      enabled: true
      namespaces: # maps to filterprocessor
        include: []
        exclude: []
        system: false
```

**Reasons**

**Attachments**
