### ISSUE TITLE
[Telemetry Operator] Concept on how to enable kubelet logs as input

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#560]
**Description**
The kubelet logs are most probably available from within the k8s data plane and with that should be collectable by fluent-bit.
Try to integrate these logs as further input into the current concept for configurable logging

See also https://github.tools.sap/cs-devops/kubernetes-logging-helm/blob/main/chart/templates/fluentbit/fluentbit-config.yaml#L68

Check for other inputs like for example used in https://www.definit.co.uk/2021/12/forwarding-tanzu-kubernetes-grid-logs-to-vrealize-log-insight-cloud-using-the-fluent-bit-package/

**Comment by a-thaler** [comment]
I had a first experiment and realized that there are two receivers: k8sobject and k8sevents

The k8seventsreceiver is going to be deprecated in favor of the k8sobjects receiver: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/24242

The k8seventsreceiver emits logs in a raw nature (not having parsed the body and log attributes being enriched) and an enriched log.

The k8sobjectreceiver emits only the raw events and parsing/enrichment still need to be done. There seem to be no good agreement yet on the actual resource attributes to use and how to simplify the parsing/enrichment as part of the k8sobject receiver. The official helm chart is using the k8sobjectreceiver already.

In my experiment with the k8seventreceiver I used that config additional:
```yaml
  processors:
    transform:
      log_statements:
      - context: log
        conditions:
        - observed_time_unix_nano == 0
        statements:
        - set(observed_time, Now())
      - context: log
        conditions:
        - time_unix_nano == 0
        statements:
        - set(time, observed_time)
    filter:
      logs:
        log_record:
          - attributes["event.domain"] == "k8s"
```
The filter is dropping the raw logs. The processor assures that the observedTime and the time is always set as the SAP Cloud Logging service had a problem with a missing time.

Indeed, the time gets only set if the timestamp gets parsed from the actual log body (enriched log), otherwise the observedTime is set.
