### ISSUE TITLE
[OTLP output] Support token prefix

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#593]
**Description**
When defining an otlp output usually a token-based authentication via a header is required. Hereby, the token itself usually gets referenced from a secret, however, the token prefix (like Bearer) might not be part of the secret value.

Goal is to support referencing a token by secret and still having a chance to provide the additional token prefix.

As example assume the below config where "xyz" is the sensitive part which should be provided by a secretRef. The "Api-Token" is not part of that secret value.
```
  output:
      otlp:
          endpoint:
              value: icke.com
          headers:
              - name: Authorization
                value: Api-Token xyz
```

Proposals:
```
  output:
      otlp:
          endpoint:
            value: icke.com
          headers:
          - name: Authorization
             valueFrom:
               secretRef: 
             prefix: Api-Token

  output:
      otlp:
          endpoint:
            value: icke.com
          authorization:
            token:
              valueFrom:
                secretRef: 
              type: Api-Token
```

Criterias:
- API got enhanced so that a user can provide the token via a secret and the prefix via a config value
- New API is documented and tested
- Separator is handled in en expected way (either space is always enforced or dedicated option)

**Reasons**

**Attachments**

**Release Notes**

```

```
