### ISSUE TITLE
[OTLP output] Support additional endpoint path

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#594]
**Description**
The OTLP endpoint for pushing metrics can be specified in the OTLP output either with a secretRef or as plain value. There are scenarios like with Dynatrace where the endpoint gets constructed out of the dynamic environment URL plus a static path. Such setup is not supported currently.

Goal is to enhance the API so that the environment URL can be specified via a secretRef plus an additional plain text path addition.

As an example take a dynatrace config below. Here the "https://icke.com/api" part will be provided by a secretRef while "v2/otlp" is specific for otlp ingestion and needs to be added plain.
```
output:
        otlp:
            protocol: http
            endpoint:
                value: https://icke.com/api/v2/otlp
```

API Proposal:
```yaml
output:
        otlp:
            protocol: http
            endpoint:
                value: https://icke.com/api
                path: /v2/otlp/v1/traces

                
```

It seems best to support a custom path for HTTP protocol only which will configure the "traces_endpoint" attribute always. By default it will take "/v1/traces".

**Criteria**
- As a user I can define a custom path provided in a static way (no secret ref) for my HTTP based OTLP endpoint
- The path is overriding the typical "/v1/traces" suffix, so users need to provide it as part of the custom path
- The validation will fail if the attribute is used with GRPC

**Reasons**

**Attachments**

**Release Notes**

```

```
