### ISSUE TITLE
Align Telemetry Pipeline Statuses with Kubernetes API Conventions

### ISSUE THREAD

**Issue by skhalash** [kyma-project/telemetry-manager#601]
**Description**

Align LogPipeline, LogParser, TracePipeline, and MetricPipeline statuses with [Kubernetes API Conventions](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties):

* Use metav1.Condtion instead of custom condition types
* Use `meta.SetStatusCondition` for transitions instead of custom transition handling code.
* Have a static, deterministically sorted conditions list instead of a dynamic list.
* Think about how to integrate Gateway/Agent failures or crashes into the status, in addition to addressing readiness.

**Reasons**

When we initially designed the first Telemetry Pipeline Custom Resources (CRs), we were unaware of the Kubernetes API Conventions related to status. Consequently, we implemented our own Condition types that resembled but were not identical to, metav1.Conditions. Additionally, we manually managed the transition of conditions and implemented a dynamic condition list. This resulted in the list being cleared whenever a running pipeline jumps back to the pending state, contradicting API conventions, complicating implementation, and potentially causing confusion for end-users. It's essential to note that the Telemetry controller monitors statuses and reflects them in the Telemetry CR status. Therefore, implementing this change will not only adhere to conventions but also simplify the overall process.

**Attachments**

Possible example, the exact details must be refined (MetricPipeline):
```yaml
status:
  conditions:
  - lastTransitionTime: "2022-03-14T20:09:36Z"
    message: Has no missing secret references
    reason: ReferencedSecretMissing
    status: "False"
    type: ReferencedSecretMissing
  - lastTransitionTime: "2022-03-14T20:10:26Z"
    message: Metric gateway Deployment is ready
    reason: MetricGatewayReady
    status: "True"
    type: MetricGatewayReady
  - lastTransitionTime: "2022-03-14T20:10:26Z"
    message: Metric agent DaemonSet is not ready
    reason: MetricAgentReady
    status: "False"
    type: MetricAgentReady
  - lastTransitionTime: "2022-03-14T20:10:26Z"
    message: Metric agent DaemonSet is not ready
    reason: MetricAgentNotReady
    status: "False"
    type: Running
```

**Related Issues**
https://github.com/kyma-project/telemetry-manager/issues/425
