### ISSUE TITLE
Disable scrape metrics by default

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#661]
**Description**
When using the prometheus or istio feature of the MetricPipeline, for every source typical scrape metrics are getting produced, concrete:
- scrape_duration_seconds
- scrape_samples_scraped
- scrape_samples_post_metric_relabeling
- scrape_series_added
- up

These are rather technical metrics very useful for debugging a problem. However, they are also causing data for a price, so they should be configurable and probably disabled by default.

**Criterias**
- As a user I will not push the mentioned metrics by default
- There is an API either on pipeline level or module level to enable the metrics, so that I can debug problems
- 
**Reasons**

**Attachments**

**Release Notes**

```

```

**Comment by hisarbalik** [comment]
- Metric gateway filter-out the diagnostic metrics by default for input type `istio` and `prometheus` when they enabled
- When diagnostic metrics are required, collection of diagnostic metrics have to be enabled explicitly per input type, like :

```yaml
apiVersion: telemetry.kyma-project.io/v1alpha1
kind: MetricPipeline
metadata:
  name: backend
spec:
  input:
    prometheus:
      enabled: true
      diagnosticMetrics:
        enabled: true
  output:
    otlp:
      endpoint:
        value: https://backend.example.com:4317
```
