### ISSUE TITLE
Spike for hardened prometheus setup

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#770]
**Description**

Run prometheus in a minimal setup in a hardened way:
- which additional resources are required (like networkPolicies)
- required istio settings
- what if the status is unhealthy because of a firing alert and prometheus restarts, will a recovery from the alert be detected
- can there be flaky alerts
- what is the actual footprint of  prometheus in regards to memory/cpu?
- What can be disabled on the prometheus instance? Any typical hardening procedure which we can apply?
- Make a conscious decision about needed sidecars. If not used, how to compensate the functionality.
- 

**Reasons**

**Attachments**

**Release Notes**

```

```

**Comment by a-thaler** [comment]
We agreed that the first 4 points don't need to be evaluated as part of the epic preparations and don't need to be done as part of the story

**Comment by hisarbalik** [comment]
Following setup used for spike :

<details>
  <summary>Test deployment</summary>

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: prometheus
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: prometheus

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
  namespace: prometheus
rules:
- apiGroups: [""]
  resources: ["serviceaccounts", "services", "endpoints", "pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
  namespace: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: prometheus
--- 
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-conf
  namespace: prometheus
  labels:
    name: prometheus-conf
data:
  prometheus.rules: |-
    groups:
    - name: alert.rules
      rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: "critical"
        annotations:
          summary: "Endpoint {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minutes."

  prometheus.yml: |
    global:
      scrape_interval: 10s
      evaluation_interval: 10s
    rule_files:
      - /etc/prometheus/prometheus.rules
    alerting:
      alertmanagers:
      - static_configs:
        - targets:
          - 'localhost:9093'
    scrape_configs:
    - job_name: 'kubernetes-service-endpoints'

      kubernetes_sd_configs:
        - role: endpoints
      relabel_configs:
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
          action: replace
          target_label: __scheme__
          regex: (https?)
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
          action: replace
          target_label: __address__
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
        - source_labels: [__meta_kubernetes_namespace]
          action: drop
          regex: kube-system
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: namespace
        - source_labels: [__meta_kubernetes_service_name]
          action: replace
          target_label: service
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: pod
        - source_labels: [__meta_kubernetes_pod_node_name]
          action: replace
          target_label: node
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus
      containers:
        - name: prometheus
          image: hbalik/promcustom
          args:
            - "--storage.tsdb.retention.time=12h"
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
            - '--web.enable-lifecycle'
          ports:
            - containerPort: 9090
          resources:
            requests:
              memory: 32Mi
            limits:
              memory: 128Mi
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
            - name: prometheus-storage-volume
              mountPath: /prometheus/
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-conf
        - name: prometheus-storage-volume
          emptyDir:
            sizeLimit: 500Mi

---

apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: prometheus
spec:
  type: ClusterIP
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
```

</details>

With this spike, we focused on resource footprints of prometheus installation compared with official docker image and custom image with reduces plugin set.
Whole setup tested on a Kyma cluster with telemetry manager installed and deployed TracePipeline, MetricPipeline wirth agent setup, and a LogPipeline. 
All deployed Pipelines loaded some synthetic load to force constant real metric generation to ensure that the prometheus is under constant load. 

Conclusion
- There are no resource footprint difference between custom prometheus docker image and official docker image observed, overall memory consumption under high load was for both images around ~95Mib and CPU usage was 0.007
- To build custom image, following steps are required
   - Download official release artefacts from Prometheus project 
   - Provide custom `plugins.yml` file, which will contains list of desired plugins for build, file have to be in root directory
   - Provide environment variables `DOCKER_REPO`, `DOCKER_IMAGE_TAG`, `DOCKER_ARCHS`, and `DOCKER_IMAGE_NAME`
   - Call following make targets to build custom docker image 
        ```bash
        make plugins
        make promu
        promu crossbuild -p linux/amd64
        make npm_licenses
        make common-docker-amd64
        ```
- Setup works without any sidecar injected, however, prometheus deployment have to be rolled-out after any configuration changes

**Comment by rakesh-garimella** [comment]
> which additional resources are required (like networkPolicies)
<details>
  <summary>network policy</summary>
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: prom-network-policy
  namespace: kyma-system
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/instance: prometheus
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kyma-system
      podSelector:
        matchLabels:
          app.kubernetes.io/instance: telemetry
          control-plane: telemetry-operator
    ports:
    - port: 9090
      protocol: TCP
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kyma-system
      podSelector:
        matchLabels:
          app.kubernetes.io/instance: telemetry
          control-plane: telemetry-operator
    ports:
    - port: 9090
      protocol: TCP
  ```
  </details>

> required istio settings
Prometheus will not be part of the istio service mesh as documented in following ADR: https://github.com/kyma-project/telemetry-manager/blob/main/docs/contributor/arch/005-do-not-make-prometheus-part%20of-the-istio-service-mesh.md
