### ISSUE TITLE
Module status indicates a gateway problem if secret is missing

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#971]
**Description**
If you define a TracePipeline with missing secret, then the configuration gets not generated and the deployment of a gateway gets prevented. The module CR status unfortunately reflects that the gateway is unhealthy instead of indicating the missing secret problem.

the tracePipeline status looks like this:
```yaml
  status:
    conditions:
    - lastTransitionTime: "2024-03-26T16:00:58Z"
      message: Trace gateway Deployment is not ready
      observedGeneration: 1
      reason: DeploymentNotReady
      status: "False"
      type: GatewayHealthy
    - lastTransitionTime: "2024-03-26T16:00:58Z"
      message: One or more referenced Secrets are missing
      observedGeneration: 1
      reason: ReferencedSecretMissing
      status: "False"
      type: ConfigurationGenerated
    - lastTransitionTime: "2024-03-26T16:00:58Z"
      message: '[NOTE: The "Pending" type is deprecated] One or more referenced Secrets
        are missing'
      observedGeneration: 1
      reason: ReferencedSecretMissing
      status: "True"
      type: Pending
```

The module CR looks like this:
```yaml
  status:
    conditions:
    - lastTransitionTime: "2023-09-07T12:44:45Z"
      message: No pipelines have been deployed
      observedGeneration: 2
      reason: NoPipelineDeployed
      status: "True"
      type: LogComponentsHealthy
    - lastTransitionTime: "2023-09-07T12:44:45Z"
      message: Trace gateway Deployment is not ready
      observedGeneration: 2
      reason: TraceGatewayDeploymentNotReady
      status: "False"
      type: TraceComponentsHealthy
    - lastTransitionTime: "2024-01-16T13:27:04Z"
      message: No pipelines have been deployed
      observedGeneration: 2
      reason: NoPipelineDeployed
      status: "True"
      type: MetricComponentsHealthy
    endpoints: {}
    state: Warning
```

**Expected result**
The modules TraceComponentsHealthy status is "ReferencedSecretMissing"

**Actual result**
The modules TraceComponentsHealthy status is "TraceGatewayDeploymentNotReady"

**Steps to reproduce**

**Troubleshooting**

**Release Notes**

```

```
